package com.bjxiyang.zhinengshequ.myapplication.bianlidian;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.bjxiyang.zhinengshequ.myapplication.bianlidian.GouWuChe;

import com.bjxiyang.zhinengshequ.myapplication.bianlidian.GouWuCheDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig gouWuCheDaoConfig;

    private final GouWuCheDao gouWuCheDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        gouWuCheDaoConfig = daoConfigMap.get(GouWuCheDao.class).clone();
        gouWuCheDaoConfig.initIdentityScope(type);

        gouWuCheDao = new GouWuCheDao(gouWuCheDaoConfig, this);

        registerDao(GouWuChe.class, gouWuCheDao);
    }
    
    public void clear() {
        gouWuCheDaoConfig.clearIdentityScope();
    }

    public GouWuCheDao getGouWuCheDao() {
        return gouWuCheDao;
    }

}
